version: '3.6'

services:
  smarthome-gui:
    image: stargazer74/smarthome-gui:arm32-latest
    ports:
      - "8080:80"
    container_name: smarthome-gui
    restart: unless-stopped
    networks:
      - default

  apigateway:
    image: stargazer74/smarthome-apigateway:arm32-latest
    ports:
      - "7080:8080"
    container_name: apigateway
    restart: unless-stopped
    networks: 
      - default

networks:
  default:
    external:
      name: smarthome-assistant-environment_smarthome