version: '3.6'

services: 
  phpmyadmin_smarthome:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_smarthome
    restart: unless-stopped
    environment: 
      - PMA_PORT=3306
      - PMA_HOST=mysql_smarthome_shoppinglist
    ports: 
      - 48080:80
    depends_on: 
      - mysql_smarthome_shoppinglist
    networks: 
      - smarthome-assistant

  mysql_smarthome_shoppinglist:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shoppinglist
    container_name: mysql_smarthome_shoppinglist
    restart: unless-stopped
    networks: 
      - smarthome-assistant
    volumes: 
      - ./mysql/.docker/build-ressources:/docker-entrypoint-initdb.d

networks:
  smarthome-assistant: