version: '3.6'

services:

  phpmyadmin_menu-service:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_menu-service
    restart: unless-stopped
    environment: 
      - PMA_PORT=3306
      - PMA_HOST=mysql_menu_service
    ports: 
      - 18080:80
    depends_on: 
      - mysql_menu_service
    networks: 
      - smarthome

  mysql_menu_service:
    image: mariadb:10.4
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=menu_service
    container_name: mysql_menu_service
    restart: unless-stopped
    networks: 
      - smarthome

  phpmyadmin_shoppinglist:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_shoppinglist
    restart: unless-stopped
    environment: 
      - PMA_PORT=3306
      - PMA_HOST=mysql_shoppinglist
    ports: 
      - 28080:80
    depends_on: 
      - mysql_shoppinglist
    networks: 
      - smarthome

  mysql_shoppinglist:
    image: mariadb:10.4
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shoppinglist
      - MYSQL_USER=shoppinglist
      - MYSQL_PASSWORD=shoppinglist
    container_name: mysql_shoppinglist
    restart: unless-stopped
    networks: 
      - smarthome
    volumes: 
      - ./maria_shoppinglist/.docker/build-ressources/dump:/docker-entrypoint-initdb.d

networks:
  smarthome: