version: '3.6'

services:
  nginx:
    build: ./nginx/.docker
    ports: 
          - "7443:443"
          - "7086:80"
    container_name: nginx
    restart: unless-stopped
    networks: 
      - smarthome
    volumes: 
      - /home/chris/Development/smarthome-gui/dist/smarthome-gui:/usr/share/nginx/html

networks:
  smarthome: