version: '3.6'

services:
  apigateway:
    image: stargazer74/smarthome-apigateway:latest
    ports:
      - "7080:8080"
      - "7001:5005"
    container_name: apigateway
    restart: unless-stopped
    environment: 
      - JDK_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks: 
      - smarthome

  menu-service:
    image: stargazer74/menu-service:latest
    ports:
      - "2080:8080"
      - "2001:5005"
    container_name: menu-service
    restart: unless-stopped
    environment: 
      - JDK_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_menu_service:3306/menu_service?autoReconnect=true&useSSL=false
    networks: 
      - smarthome

networks:
  smarthome: