version: '3.6'

services:
  smarthome-gui:
    image: stargazer74/smarthome-gui:arm32-latest
    ports:
      - "80:80"
    container_name: smarthome-gui
    restart: unless-stopped
    networks:
      - default

  apigateway:
    image: stargazer74/smarthome-apigateway:arm32-latest
    ports:
      - "7080:8080"
    container_name: apigateway
    restart: unless-stopped
    networks: 
      - default

  menu-service:
    image: stargazer74/menu-service:arm-32-latest
    ports:
      - "2080:8080"
      - "2001:5005"
    container_name: menu-service
    restart: unless-stopped
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://maria_smarthome:3306/menu_service?autoReconnect=true&useSSL=false
    networks: 
      - default

networks:
  default:
    external:
      name: smarthome-assistant-environment_smarthome