version: '3.6'

services:
  phpmyadmin_smarthome:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_smarthome
    restart: unless-stopped
    environment: 
      - PMA_PORT=3306
      - PMA_HOST=maria_smarthome
    ports: 
      - 28080:80
    depends_on: 
      - maria_smarthome
    networks: 
      - smarthome

  maria_smarthome:
    image: mariadb:10.4
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=menu_service
    container_name: maria_smarthome
    restart: unless-stopped
    networks: 
      - smarthome

networks:
  smarthome: