version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "18080:8080"
    container_name: jenkins
    restart: unless-stopped
    volumes: 
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_data:
    driver: local